# Generated by Django 3.0.5 on 2020-04-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0003_auto_20200419_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='upc',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
